"""MotionCaption — Motion Typography Engine for Python.

Deterministic, plugin-based animated subtitles. See ``docs/architecture.md``
for the design contract.
"""

from __future__ import annotations

from motion_caption import (
    animations,
    easing,
    emphasis,
    exporters,
    ir,
    layout,
    models,
    placement,
    reading,
    render,
    segmentation,
    themes,
    typography,
)
from motion_caption.animations import (
    ANIMATION_REGISTRY,
    AnimationConfig,
    WordItem,
    animate_segment,
    animate_word,
    build_word_items,
)
from motion_caption.canvas import AspectRatio, Canvas, StandardResolution
from motion_caption.easing import EasingKind, EasingSpec, compile_spec
from motion_caption.emphasis import apply_emphasis, importance_to_mode
from motion_caption.exporters import (
    EXPORTER_REGISTRY,
    AssOptions,
    Exporter,
    ExporterResult,
    build_ass,
)
from motion_caption.ir import (
    AIContribution,
    AnimationTrack,
    CaptionRequest,
    CompileOptions,
    KeyframeTrack,
    PlacementRegion,
    ResolvedBackground,
    ResolvedBorder,
    ResolvedFont,
    ResolvedGlow,
    ResolvedPadding,
    ResolvedShadow,
    ResolvedStroke,
    ResolvedTypography,
    SpeakerTrack,
    StyleTrack,
    SubtitleEvent,
    SubtitleTimeline,
    Track,
    WordEvent,
)
from motion_caption.layout import LayoutEngine, LayoutOptions, PlacedBlock, lay_out
from motion_caption.models import (
    Box,
    Color,
    DesignSpace,
    EmphasisMode,
    FillSpec,
    GradientFill,
    GradientStop,
    Keyframe,
    KeyframeTimeline,
    Length,
    Padding,
    Point,
    PropertyKind,
    Region,
    RegionTimeline,
    Resolution,
    ResolutionContext,
    ScalePolicy,
    Segment,
    Size,
    Transcript,
    Unit,
    Word,
    WordTimestamp,
)
from motion_caption.placement import (
    PLACEMENT_REGISTRY,
    PLATFORM_SAFE_AREAS,
    Face,
    PlacementConfig,
    SafeArea,
    avoid_faces,
    place,
    platform_safe_area,
)
from motion_caption.reading import adjust_segments, analyze, difficulty_of
from motion_caption.render import CaptionRenderer, RenderOptions, TimelineRenderer
from motion_caption.segmentation import (
    SegmentationConfig,
    Segmenter,
    segment_transcript,
)
from motion_caption.themes import (
    AnimationPersonality,
    EmphasisAppearance,
    ResolvedTheme,
    ThemeSpec,
    builtin_themes,
    load_theme,
    resolve_theme,
)
from motion_caption.typography import (
    BackgroundSpec,
    FontManager,
    FontRef,
    FontStack,
    MeasuredBlock,
    TextAlign,
    TextMeasurer,
    TextStyle,
)

__version__ = "0.1.0"

__all__ = [
    "AIContribution",
    "AnimationPersonality",
    "ANIMATION_REGISTRY",
    "AnimationConfig",
    "AnimationTrack",
    "AspectRatio",
    "AssOptions",
    "BackgroundSpec",
    "Box",
    "CaptionRenderer",
    "CaptionRequest",
    "Canvas",
    "Color",
    "CompileOptions",
    "DesignSpace",
    "EmphasisAppearance",
    "EmphasisMode",
    "EasingKind",
    "EasingSpec",
    "Exporter",
    "ExporterResult",
    "EXPORTER_REGISTRY",
    "Face",
    "FillSpec",
    "GradientFill",
    "GradientStop",
    "FontManager",
    "FontRef",
    "FontStack",
    "Keyframe",
    "KeyframeTimeline",
    "KeyframeTrack",
    "LayoutEngine",
    "LayoutOptions",
    "Length",
    "MeasuredBlock",
    "Padding",
    "PlacementRegion",
    "PLACEMENT_REGISTRY",
    "PLATFORM_SAFE_AREAS",
    "PlacementConfig",
    "PlacedBlock",
    "Point",
    "PropertyKind",
    "ReadingStats",
    "Region",
    "RegionTimeline",
    "Registry",
    "RenderOptions",
    "ResolvedBackground",
    "ResolvedBorder",
    "ResolvedFont",
    "ResolvedGlow",
    "ResolvedPadding",
    "ResolvedShadow",
    "ResolvedStroke",
    "ResolvedTheme",
    "ResolvedTypography",
    "Resolution",
    "ResolutionContext",
    "SafeArea",
    "ScalePolicy",
    "Segment",
    "SegmentationConfig",
    "Segmenter",
    "Size",
    "SpeakerTrack",
    "StandardResolution",
    "StyleTrack",
    "SubtitleEvent",
    "SubtitleTimeline",
    "TextAlign",
    "TextMeasurer",
    "TextStyle",
    "ThemeSpec",
    "TimelineRenderer",
    "Track",
    "Transcript",
    "Unit",
    "Word",
    "WordEvent",
    "WordItem",
    "WordTimestamp",
    "adjust_segments",
    "analyze",
    "animate_segment",
    "animate_word",
    "animations",
    "apply_emphasis",
    "avoid_faces",
    "build_ass",
    "build_word_items",
    "builtin_themes",
    "compile_spec",
    "difficulty_of",
    "easing",
    "emphasis",
    "exporters",
    "importance_to_mode",
    "ir",
    "layout",
    "lay_out",
    "load_theme",
    "models",
    "place",
    "placement",
    "platform_safe_area",
    "reading",
    "render",
    "resolve_theme",
    "segmentation",
    "segment_transcript",
    "themes",
    "typography",
]
