"""MotionCaption — Motion Typography Engine for Python.

Deterministic, plugin-based animated subtitles. See ``docs/architecture.md``
for the design contract.
"""

from __future__ import annotations

from motion_caption import (
    animations,
    easing,
    emphasis,
    layout,
    models,
    placement,
    reading,
    segmentation,
    themes,
    typography,
)
from motion_caption.animations import (
    ANIMATION_REGISTRY,
    AnimationConfig,
    WordItem,
    animate_segment,
    animate_word,
    build_word_items,
)
from motion_caption.canvas import AspectRatio, Canvas, StandardResolution
from motion_caption.easing import EasingKind, EasingSpec, compile_spec
from motion_caption.emphasis import apply_emphasis, importance_to_mode
from motion_caption.layout import LayoutEngine, LayoutOptions, PlacedBlock, lay_out
from motion_caption.models import (
    Box,
    Color,
    DesignSpace,
    EmphasisMode,
    FillSpec,
    GradientFill,
    GradientStop,
    Keyframe,
    KeyframeTimeline,
    Length,
    Padding,
    Point,
    PropertyKind,
    Region,
    RegionTimeline,
    Resolution,
    ResolutionContext,
    ScalePolicy,
    Segment,
    Size,
    Transcript,
    Unit,
    Word,
    WordTimestamp,
)
from motion_caption.placement import (
    PLACEMENT_REGISTRY,
    PLATFORM_SAFE_AREAS,
    Face,
    PlacementConfig,
    SafeArea,
    avoid_faces,
    place,
    platform_safe_area,
)
from motion_caption.reading import ReadingStats, adjust_segments, analyze, difficulty_of
from motion_caption.registry import Registry
from motion_caption.segmentation import (
    SegmentationConfig,
    Segmenter,
    segment_transcript,
)
from motion_caption.themes import (
    AnimationPersonality,
    EmphasisAppearance,
    ResolvedTheme,
    ThemeSpec,
    builtin_themes,
    load_theme,
    resolve_theme,
)
from motion_caption.typography import (
    BackgroundSpec,
    FontManager,
    FontRef,
    FontStack,
    MeasuredBlock,
    TextAlign,
    TextMeasurer,
    TextStyle,
)

__version__ = "0.1.0"

__all__ = [
    "AnimationPersonality",
    "ANIMATION_REGISTRY",
    "AnimationConfig",
    "AspectRatio",
    "BackgroundSpec",
    "Box",
    "Canvas",
    "Color",
    "DesignSpace",
    "EmphasisAppearance",
    "EmphasisMode",
    "EasingKind",
    "EasingSpec",
    "Face",
    "FillSpec",
    "GradientFill",
    "GradientStop",
    "FontManager",
    "FontRef",
    "FontStack",
    "Keyframe",
    "KeyframeTimeline",
    "LayoutEngine",
    "LayoutOptions",
    "Length",
    "MeasuredBlock",
    "Padding",
    "PLACEMENT_REGISTRY",
    "PLATFORM_SAFE_AREAS",
    "PlacementConfig",
    "PlacedBlock",
    "Point",
    "PropertyKind",
    "ReadingStats",
    "Region",
    "RegionTimeline",
    "Registry",
    "Resolution",
    "ResolutionContext",
    "ResolvedTheme",
    "SafeArea",
    "ScalePolicy",
    "Segment",
    "SegmentationConfig",
    "Segmenter",
    "Size",
    "StandardResolution",
    "TextAlign",
    "TextMeasurer",
    "TextStyle",
    "ThemeSpec",
    "Transcript",
    "Unit",
    "Word",
    "WordItem",
    "WordTimestamp",
    "adjust_segments",
    "analyze",
    "animate_segment",
    "animate_word",
    "animations",
    "apply_emphasis",
    "avoid_faces",
    "build_word_items",
    "builtin_themes",
    "compile_spec",
    "difficulty_of",
    "easing",
    "emphasis",
    "importance_to_mode",
    "layout",
    "lay_out",
    "load_theme",
    "models",
    "place",
    "placement",
    "platform_safe_area",
    "reading",
    "resolve_theme",
    "segmentation",
    "segment_transcript",
    "themes",
    "typography",
]
